# Generated by Django 4.1.1 on 2023-03-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bin_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_color', models.CharField(max_length=100)),
                ('bin_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('Bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bin_name', models.CharField(max_length=100)),
                ('Bin_address1', models.CharField(max_length=100)),
                ('Bin_address2', models.CharField(max_length=100)),
                ('Bin_address3', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('distance_KM', models.CharField(max_length=100)),
                ('total_time', models.TimeField(default=0)),
                ('Bin_date', models.DateField(default=0)),
                ('Bin_status', models.CharField(max_length=50)),
                ('Bin_color', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bin_color', verbose_name='bin_color')),
            ],
        ),
        migrations.CreateModel(
            name='complaintpost',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_landmark', models.CharField(max_length=100)),
                ('bin_number', models.CharField(max_length=100)),
                ('c_complant', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=200)),
                ('driver_email', models.CharField(max_length=100, unique=True)),
                ('driver_phone', models.BigIntegerField()),
                ('driver_licence', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='')),
                ('Allocatted_bin', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_email', models.CharField(max_length=100, unique=True)),
                ('emp_phone', models.BigIntegerField()),
                ('emp_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('employee_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.employee', verbose_name='emp_name')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_no', models.CharField(max_length=100)),
                ('regd_owner', models.CharField(max_length=100)),
                ('reg_address', models.CharField(max_length=100)),
                ('makers_class', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workupdation',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(default=0)),
                ('Date', models.DateField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('Bin_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name')),
                ('Driver_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.driver', verbose_name='driver_name')),
                ('Location', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name='region')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleingday',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('region', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name='region')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name=' region'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.vehicle', verbose_name='register_no'),
        ),
        migrations.AddField(
            model_name='bins',
            name='Bin_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='bins',
            name='collections_day',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.scheduleingday', verbose_name='day'),
        ),
    ]
