# Generated by Django 4.1.1 on 2023-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_back',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('feedbacktype', models.CharField(max_length=1000, null=True)),
                ('des_feedback', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
