# Generated by Django 4.1.1 on 2023-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_feed_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('prd_name', models.CharField(default='', max_length=100)),
                ('prd_discription', models.CharField(max_length=200, unique=True)),
                ('prd_price', models.IntegerField(max_length=15)),
            ],
        ),
    ]
