# Generated by Django 4.1.1 on 2023-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prd_img',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
