# Generated by Django 4.1.1 on 2023-03-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Account',
        ),
    ]
