# Generated by Django 4.1.1 on 2023-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_cart_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
