# Generated by Django 4.1.1 on 2023-04-17 07:13

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_collection_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location1',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
