# Generated by Django 4.1.1 on 2023-04-18 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_location_location1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_engine_no', message='Engine no. can only contain uppercase letters, digits, and hyphens', regex='^[A-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_insurance_no', message='Insurance no. must be in the format XX 00 XX 0000', regex='^[A-Z]{2}\\s[0-9]{2}\\s[A-Z]{2}\\s[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='register_no',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_register_no', message='Register no. must be in the format XX 00 XX 0000', regex='^[A-Z]{2}\\s[0-9]{2}\\s[A-Z]{2}\\s[0-9]{4}$')]),
        ),
    ]
