# Generated by Django 4.1.1 on 2023-04-19 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_vehicle_engine_alter_vehicle_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bins',
            name='Bin_address1',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^[\\w\\-\\. ]+$')]),
        ),
        migrations.AlterField(
            model_name='bins',
            name='Bin_address2',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^[\\w\\-\\. ]+$')]),
        ),
        migrations.AlterField(
            model_name='bins',
            name='Bin_address3',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid address.', regex='^[\\w\\-\\. ]+$')]),
        ),
        migrations.AlterField(
            model_name='bins',
            name='Bin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bins',
            name='Bin_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bins',
            name='Bin_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bins',
            name='distance_KM',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.RegexValidator(message='Invalid distance.', regex='^\\d+(\\.\\d{1,2})?$')]),
        ),
        migrations.AlterField(
            model_name='bins',
            name='pincode',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Invalid pincode.', regex='^[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='bins',
            name='total_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.DeleteModel(
            name='Collection_bin',
        ),
    ]
